server.port=${PORT:3000}
firebase.credentials.path=${FIREBASE_CREDENTIALS_PATH:}
payments.provider=${PAYMENTS_PROVIDER:mock}
payments.currency=${PAYMENTS_CURRENCY:BOB}
payments.mercadopago.base-url=${MP_BASE_URL:https://api.mercadopago.com}
payments.mercadopago.access-token=${MP_ACCESS_TOKEN:}
payments.mercadopago.notification-url=${MP_NOTIFICATION_URL:}
payments.mercadopago.sandbox=${MP_SANDBOX:true}
